export const sizes = [
    { value: "SMALL", label: "KICHIK" },
    { value: "MEDIUM", label: "O'RTACHA" },
    { value: "BIG", label: "KATTA" },
    { value: "SIZE_39", label: "39" },
    { value: "SIZE_40", label: "40" },
    { value: "SIZE_41", label: "41" },
    { value: "SIZE_42", label: "42" },
    { value: "SIZE_43", label: "43" },
    { value: "SIZE_44", label: "44" },
    { value: "SIZE_45", label: "45" },
    { value: "SIZE_28", label: "28" },
    { value: "SIZE_29", label: "29" },
    { value: "SIZE_30", label: "30" },
    { value: "SIZE_31", label: "31" },
    { value: "SIZE_32", label: "32" },
    { value: "SIZE_33", label: "33" },
    { value: "SIZE_34", label: "34" },
    { value: "SIZE_35", label: "35" },
    { value: "SIZE_36", label: "36" },
    { value: "S", label: "S" },
    { value: "M", label: "M" },
    { value: "L", label: "L" },
    { value: "XL", label: "XL" },
    { value: "XXL", label: "XXL" },
    { value: "XXXL", label: "XXXL" },
];